### ISSUE TITLE
React Functional Components with Hooks

### ISSUE THREAD

**Issue by DarkxDev** [DarkxDev/math-magicians#4]
This is how I used hooks in my Calculator.js file:

- useState returns an array with two values: the current state value and a function to update it.
- In this code, useState(null) is used to set the initial state of total, next, and operation to null.
- The setTotal, setNext, and setOperation functions are used to update the state values.
- The handleClick function is called when a button is clicked. It uses the calculate function to calculate the result and update the state values using the setTotal, setNext, and setOperation functions.

**Comment by Whoistolu** [comment]
### Hi @DarkxDev 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
